#!/usr/bin/env julia
############################################################
# scripts/export_env.jl — capture THIS machine's package versions
#
# Run this on the machine whose environment currently works, then commit the two
# files it writes.  The VM then reproduces that exact stack.
#
# Why this script exists: the estimation entry points load twelve registered
# packages, but the repo's Project.toml declares only QuasiMonteCarlo — the rest
# resolve from the user's DEFAULT (shared) environment.  A shared default env is
# not reproducible: it drifts as other projects add packages, and it is not part
# of the repo.  This script reads the versions actually loaded here and pins them
# into a project-local Project.toml, which makes the repo self-contained without
# changing anything about how the code runs on this machine.
#
# Usage (from the repo root, using your normal environment):
#   julia scripts/export_env.jl
#
# Writes: Project.toml  (deps + exact = version pins, UUIDs from the registry)
#         Manifest.toml (full resolved tree, via Pkg.resolve)
############################################################

using Pkg, Printf, TOML

# The packages the two estimation entry points need. Deliberately excludes Plots
# and LaTeXStrings (figures) and HTTP/XLSX/Arrow (data construction): a compute VM
# runs the estimation only, and those pull large binary artifacts that add install
# time and failure modes without being used.
const ESTIMATION_DEPS = [
    "CSV", "Clustering", "DataFrames", "Distributions", "FastGaussQuadrature",
    "Interpolations", "JSON3", "Optim", "Parameters", "QuasiMonteCarlo",
]

# Standard-library modules the code loads. They need declaring for a project
# environment to load them, but carry no version.
const STDLIBS = [
    "Dates", "DelimitedFiles", "LinearAlgebra", "Printf", "Random",
    "Serialization", "SparseArrays", "Statistics",
]

const REPO_ROOT = abspath(joinpath(@__DIR__, ".."))

# Versions as installed in the environment this script is run from. Pkg resolves
# names to UUIDs against the registry, so no UUID is ever written by hand.
installed = Pkg.dependencies()
byname    = Dict(v.name => v for (_, v) in installed)

@printf("Environment: %s\n", Base.active_project())
@printf("Julia:       %s\n\n", VERSION)

missing_pkgs = String[]
found        = Tuple{String,String}[]      # (name, version)
for p in ESTIMATION_DEPS
    if haskey(byname, p) && byname[p].version !== nothing
        push!(found, (p, string(byname[p].version)))
    else
        push!(missing_pkgs, p)
    end
end

if !isempty(missing_pkgs)
    @printf("NOT LOADED in this environment: %s\n", join(missing_pkgs, ", "))
    println("Run this script from the environment you normally use for the project,")
    println("or `Pkg.add` the missing packages there first. Nothing was written.")
    exit(1)
end

for (name, ver) in found
    @printf("  %-22s %s\n", name, ver)
end

# Build the project by NAME and let Pkg fill in UUIDs and resolve the tree; then
# pin each package to the exact version found above so the VM gets this stack.
tmp = mktempdir()
Pkg.activate(tmp)
Pkg.add([Pkg.PackageSpec(name = n, version = VersionNumber(v)) for (n, v) in found])
proj = TOML.parsefile(joinpath(tmp, "Project.toml"))

deps = Dict{String,Any}(proj["deps"])
# stdlib UUIDs come from the running Julia itself, not from a literal table
for s in STDLIBS
    id = Base.identify_package(s)
    id === nothing ? @printf("  (skipping unknown stdlib %s)\n", s) :
                     (deps[s] = string(id.uuid))
end

compat = Dict{String,Any}("julia" => string(VERSION.major, ".", VERSION.minor))
for (n, v) in found
    compat[n] = "=" * v                    # exact pin: the VM gets this version
end

open(joinpath(REPO_ROOT, "Project.toml"), "w") do io
    println(io, "# Generated by scripts/export_env.jl — do not edit by hand.")
    println(io, "# Pins the estimation stack to the versions in use on the machine")
    println(io, "# where the export was run. Restore with:")
    println(io, "#   julia --project=. -e 'using Pkg; Pkg.instantiate()'")
    println(io)
    println(io, "name = \"RoySearch\"")
    println(io)
    println(io, "[deps]")
    for k in sort(collect(keys(deps)))
        println(io, "$k = \"$(deps[k])\"")
    end
    println(io)
    println(io, "[compat]")
    for k in sort(collect(keys(compat)))
        println(io, "$k = \"$(compat[k])\"")
    end
end

# Resolve in the repo itself so the Manifest matches the pinned Project.
Pkg.activate(REPO_ROOT)
Pkg.resolve()

@printf("\nWrote %s\n      %s\n",
        joinpath(REPO_ROOT, "Project.toml"), joinpath(REPO_ROOT, "Manifest.toml"))
println("Commit both. On the VM: julia --project=. -e 'using Pkg; Pkg.instantiate()'")
