#!/usr/bin/env bash
# scripts/setup_vm.sh — provision a fresh Linux VM to run the estimation batch.
#
# Installs the pinned Julia, restores the environment from Manifest.toml, and
# precompiles. Idempotent: safe to re-run.
#
#   bash scripts/setup_vm.sh                 # uses the Julia version below
#   JULIA_VERSION=1.10.10 bash scripts/setup_vm.sh
#
# Assumes Project.toml/Manifest.toml were generated by scripts/export_env.jl on the
# machine whose environment works. Without that, `instantiate` cannot see the
# packages the code loads, because the repo's committed Project.toml declares only
# QuasiMonteCarlo and everything else resolves from a shared default environment.
set -euo pipefail

# Match the Manifest's julia_version: a Manifest is only guaranteed to instantiate
# on the minor version that wrote it.
JULIA_VERSION="${JULIA_VERSION:-1.10.10}"
JULIA_SERIES="${JULIA_VERSION%.*}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

case "$(uname -m)" in
  x86_64)          ARCH=x64;   TARBALL_ARCH=x86_64 ;;
  aarch64|arm64)   ARCH=aarch64; TARBALL_ARCH=aarch64 ;;
  *) echo "unsupported architecture $(uname -m)" >&2; exit 1 ;;
esac

echo "=== RoySearch VM setup ==="
echo "  repo:   $REPO_ROOT"
echo "  julia:  $JULIA_VERSION ($ARCH)"
echo "  cores:  $(nproc)"
echo "  memory: $(awk '/MemTotal/ {printf "%.1f GB", $2/1048576}' /proc/meminfo)"

if ! command -v julia >/dev/null 2>&1 || \
   [ "$(julia --version | awk '{print $3}')" != "$JULIA_VERSION" ]; then
  echo "--- installing Julia $JULIA_VERSION ---"
  URL="https://julialang-s3.julialang.org/bin/linux/${ARCH}/${JULIA_SERIES}/julia-${JULIA_VERSION}-linux-${TARBALL_ARCH}.tar.gz"
  curl -fsSL "$URL" -o /tmp/julia.tar.gz
  sudo mkdir -p /opt/julia
  sudo tar -xzf /tmp/julia.tar.gz -C /opt/julia --strip-components=1
  sudo ln -sf /opt/julia/bin/julia /usr/local/bin/julia
  rm -f /tmp/julia.tar.gz
fi
julia --version

echo "--- restoring the pinned environment ---"
cd "$REPO_ROOT"
julia --project=. -e '
  using Pkg
  Pkg.instantiate()          # exact versions from Manifest.toml
  Pkg.precompile()           # pay compilation once, not per batch process
  Pkg.status()
'

echo "--- smoke test: can the solver stack load? ---"
julia --project=. --threads=2 -e '
  using LinearAlgebra, SparseArrays, Statistics, Random, Distributions
  using FastGaussQuadrature, Interpolations, Parameters, Printf
  using Optim, CSV, DataFrames, Serialization, Clustering, QuasiMonteCarlo, JSON3
  println("all estimation packages load; threads = ", Threads.nthreads())
'

cat <<EOF

=== ready ===
Run the batch under tmux so it survives a dropped SSH session:

  tmux new -s roysearch
  cd $REPO_ROOT
  julia code/run_all.jl --task=estimate --concurrent

Detach with Ctrl-b d, reattach with: tmux attach -t roysearch
Logs stream to output/logs/ regardless.
EOF
